#!/bin/bash
# Attach to the development container or run a command inside it
set -e
cd "$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
if [ $# -eq 0 ]; then
  docker compose -f .devcontainer/docker-compose.yml -p coding-robot exec app bash -l
else
  docker compose -f .devcontainer/docker-compose.yml -p coding-robot exec app bash -lc "$*"
fi
